[package]
name = "cargo-bug-multiversion"
version = "0.1.0"
authors = ["Fake Author <fakeauthor@example.com>"]
edition = "2018"

[dependencies]
lazy_static = "1"

[target.'cfg(not(windows))'.dependencies]
lazy_static = "0.2"

[target.'cfg(windows)'.dependencies]
lazy_static = "0.1"
